### ISSUE TITLE
Tag releases `0.1.0` (and release `0.2.0`)

### ISSUE THREAD

**Issue by huguesbr** [fetlife/rollout-ui#5]
I believe only version `0.1.0` is released and would be great to tag the version (https://github.com/fetlife/rollout-ui/commit/18623736c38eaae4da5732248afd468e7a75db25 ? )

**Comment by reneklacan** [comment]
I made to sure to tag commits for `0.2`, `0.3` and released latest state of the code as `0.4`

**Comment by huguesbr** [comment]
Thx!!
