### ISSUE TITLE
"message kinkster" button sometimes missing

### ISSUE THREAD

**Issue by as-muncher** [fetlife/rollout-ui#9]
Hi, I find sometimes, on some peoples' profiles, that the "message kinkster" button is missing.  When the person then messages me, then the button shows again.  This doesn't happen on everyone's profile, just some peoples'.  I'm not sure if this is the correct repository for this issue, so if it isn't, could you please move it to the correct one?

**Comment by nielsenramon** [comment]
@as-muncher Definitely not the right place to post this. You can post it on the official tech support group or email support@fetlife.com.
